name: CI Event services

on:
  push:
    branches:
      - master
      - event-service
    paths:
      - service/**
  pull_request:
    branches:
      - master
      - event-service
    paths:
      - service/**

jobs:
  ci-ticket:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.2

      - name: Build
        working-directory: ./service
        run: go build -v ./...

      - name: Test
        working-directory: ./service
        run: go test -v ./...
