package error

import "errors"

var (
	ErrPayloadValidation      = errors.New("error payload validation")
	ErrQueryParam             = errors.New("error query param validation")
	ErrDB                     = errors.New("error DB")
	ErrInvalidToken           = errors.New("invalid token")
	ErrInvalidTokenFormat     = errors.New("invalid token format")
	ErrInvalidFCMToken        = errors.New("imvalid fcm token")
	ErrTokenExpired           = errors.New("token expired")
	ErrQuotaExceeded          = errors.New("daily quota exceeded")
	ErrOutOfQuota             = errors.New("out of quota")
	ErrGetFCMToken            = errors.New("error get fcm token")
	ErrCreateMessage          = errors.New("error create firebase message collection")
	ErrSendNotification       = errors.New("error send message notification")
	ErrNotFound               = errors.New("not found")
	ErrOverPaymentPeriod      = errors.New("over payment period")
	ErrInvalidStatus          = errors.New("invalid status")
	ErrNoActiveOrder          = errors.New("no active order")
	ErrInvalidSession         = errors.New("invalid session")
	ErrInvalidPaymentMethod   = errors.New("invalid payment method")
	ErrExceedMaxOrderQuantity = errors.New("exceed maximum order quantity")
	ErrExceedDailyHourLimit   = errors.New("exceed daily hours limit")
	ErrExceedAllowedOrderDays = errors.New("exceed allowed order days")
	ErrClosingDay             = errors.New("closing day")
	ErrOrderBeforeToday       = errors.New("order before today")
	ErrOrderNotFound          = errors.New("order not found")
	ErrOrderTicketNotFound    = errors.New("order ticket not found")
	ErrExternal               = errors.New("error external service")
	ErrNotImplemented         = errors.New("error not implemented")
	ErrEmptyUserName          = errors.New("empty user name")
	ErrInvalidConfig          = errors.New("invalid config")
	ErrInvalidQRString        = errors.New("invalid qr string")
	ErrUnregisteredOfficer    = errors.New("unregistered officer")
	ErrTicketSoldOut          = errors.New("ticket sold out")
)
